server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@211.238.142.22:1521:XE
    username: hr
    password: happy   
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true
  ai:
    google:
     genai: 
      api-key: 
      chat:
        options:
          model: gemini-2.5-flash-lite

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind : TRACE